# Configuration for local development environment
spring:
  profiles: h2
 
  h2:
    console:
      enabled: true
      
  datasource:
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      # Database connection pool size
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:  org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        temp:
          use_jdbc_metadata_default: false
