server:
  port: 4000

spring:
  datasource:
    url: jdbc:postgresql://rms-clouddev-final.ccadpnws7azu.us-west-1.rds.amazonaws.com:5432/resources
    username: rms_resources_app_server
    password: Uia4KdJYTz0kDTD2qSdiuo66l0lyGceIpLD5b7WF
    
  hikari:
    # Database connection pool size
    maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        temp:
          use_jdbc_metadata_default: false
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false

