# Use native profile to allow properties set locally
# Set secondary profile for current environment, defaulting to local if no environment is provided

spring:
  profiles:
    active: ${RMS_APP_PROFILE:local}
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/revature-resource-force/rms-config-files
          force-pull: true
server:
  port: 8888